name: "Move Tag v2"

on:
  push:
    tags:
      - "v2*"

jobs:
  MoveTag:
    name: "Move Tag v2"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Move v2 Tag
        uses: richardsimko/update-tag@v1
        env:
          GITHUB_TOKEN: "${{ secrets.TOMASNORRE_BOT_TOKEN }}"
        with:
          tag_name: v2