name: "Release"

on:
  push:
    tags: "v[1-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Create release"
        uses: "actions/create-release@v1"
        env:
          GITHUB_TOKEN: "${{ secrets.TOMASNORRE_BOT_TOKEN }}"
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - name: Move v2 Tag
        uses: richardsimko/update-tag@v1
        env:
          GITHUB_TOKEN: "${{ secrets.TOMASNORRE_BOT_TOKEN }}"
        with:
          tag_name: v2

      # Make New Release to Docker Hub
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_HUB_USERNAME }} --password=${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Docker Build
        run: docker build -t tomasnorre/typo3teruploader:latest Docker/

      - name: Docker Push
        run: docker push tomasnorre/typo3teruploader:latest